freebayes/freebayes

src/AlleleParser.cpp, src/AlleleParser.h, src/Makefile, src/NonCall.cpp, src/NonCall.h, src/Parameters.cpp, src/Parameters.h, src/ResultData.cpp, src/ResultData.h, src/Sample.h, src/freebayes.cpp, test/t/01_call_variants.t
When --gvcf is supplied, freebayes will output blocks for each
region that does not have a call. These have a particular format
that is not exactly the same as other records. A genotype quality
is provided, but this is just the reference quality sum adjusted
by the alternate quality sum. These are provided per-sample.
Average depth is provided across the region. Improvement of this
format is essential, and this version should stand as a
placeholder for future development!
=> add gVCF support

src/BedReader.cpp, test/t/01_call_variants.t
BED files are supposed to be able to have header lines like 'track', 'browser', ect.  To allow `freebayes` to process those, we can split only on `\t` (like the BED spec specifies) and just skip lines with only one field.
Not super important, but less confusing IMO.
=> bit stricter BED processing

src/AlleleParser.cpp
This allows specifying regions such as 1:68,152,354-68,152,418
for the --region parameter which makes copy and paste with UCSC and IGV
genome browsers easier.
=> Ignoring commas in region specification

src/LeftAlign.cpp
This is a simple change to enable bamleftalign to read BAM/SAM input with CIGAR operations from SAM 1.3 and later (specifically, "X" and "="). This patch does not change the output CIGAR format to SAM 1.3+ specifications, but it does maintain the total number of aligned bases from the input.
The following lines are example input CIGAR strings, the output from the HEAD version of bamleftalign, and the output from my patched version. The primary difference with the patch is the resolution of the "0M" operations from the current bamleftalign to non-zero operations.
Input CIGAR string with X and = operations:
`3S245=1X813=3D4=1I29=1X31=1X96=3D1=3I12=1X5=1I2=1D584=1X992=1X892=1X2=1X28=2D47=1X254=1X47=1X83=1X424=1X212=1X91=1X238=1D22=1X47=1X41=1D3=1D5=2D26=1D16=3D536=1X90=1X934=3I383=1X119=2X390 …
=> Add support for reading SAM 1.3 CIGAR operations in bamleftalign

.gitmodules, scripts/freebayes-parallel, src/AlleleParser.cpp, src/AlleleParser.h, src/Makefile, src/ResultData.cpp, src/ResultData.h, src/freebayes.cpp, test/Makefile
@ekg and @mlin ,
To start off, I updated the VCFLIB pointer so I could work on OSX.  This required changes to the Makefile, updating all of the namespaces for vcflib (vcf->vcflib). This also adds HTSLIB to the repository.  The DP-> DP_MIN was a minimal change.  Tests 1-6, 8-9,11-15,17-19 are passing.  The other test appear to be failing due to grep usage errors:
```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
[-e pattern] [-f file] [--binary-files=value] [--color=when]
[--context[=num]] [--directories=action] [--label] [--line-buffered]
[--null] [pattern] [file ...]
```
closes #238 
fixes #266
=> Updating VCFLIB submodule and format change

src/freebayes.cpp
We should not skip when we have *enough* coverage, rather we do not need
to downsample when we have *enough* coverage.
=> Bug fix in merge 96e85182c4cd1c462cf49ca06b858da8c7b99c44.

src/AlleleParser.cpp, src/NonCall.cpp, src/NonCall.h, src/ResultData.cpp
Summing noncall refCount and altCount is correct to get DP (average depth over gvcf block).  However, zero coverage sites need to be considered for the MIN_DP.  If numSites is greater than the number of noncalls we know there is a site with no coverage.  The INFO and GENOTYPE fields have been updated.
Solving #239 via @mlin
=> fixing min_depth

src/AlleleParser.cpp, src/AlleleParser.h, test/t/02_multi_bam.t
As mentioned in #187, currently FreeBayes will run with conflicting read
groups in the headers and then exit with success. The intention is to
flag this error immediately and exit with an informative message/error
code. This patch:
* Attempts to get the header from each BAM individually, ignoring the
standard input case.
* Additionally checks that the technology mapping is unique.
As described in the commit messages, this would be better if directly
supported by bamtools.
=> Ensure FreeBayes fails on multiple BAMs with conflicting read groups

src/AlleleParser.cpp, src/ResultData.cpp
DPR is mislabeled as a `Number=A` field, but writing out `Number=R` values.
Also, as @nh13 noticed, the REF allele count was wrong anyway -
printing the total depth rather than the REF depth.
Replace by FORMAT/AD which is a Number=R field now defined in the spec. Also
need to bump the VCF version to 4.2 (`Number=R` was introduced in 4.2, but AD in 4.3)
Fixes #267
=> replace FORMAT/DPR annotation by FORMAT/AD

test/t/01_call_variants.t
These seemed a bit vulnerable to incorrect output passing them.
=> Make some tests more specific

README.md
Freebayes depends on zlib, although this was not noted in the README, which is understandable because zlib is so common that a dependency on it is so easy to ignore.
=> Note unstated dependency on zlib

src/Allele.cpp, src/AlleleParser.cpp, src/AlleleParser.h, src/Parameters.cpp, src/freebayes.cpp, test/t/00_region_and_target_handling.t, test/t/01_call_variants.t, test/t/02_multi_bam.t, test/t/03_reference_bases.t
The complexity of the allele parsing algorithm that converted a read into a series of alleles made it easy for us to introduce a number of bugs, the ultimate result of which was an elimination of certain kinds of complex alleles. These commits rewrite the allele parsing logic to be simpler and easier to maintain, and resolve the underlying problem. They also resolve a number of other minor issues, such as a problem with reported depth in some contexts.
=> Improve handling of complex alleles

Makefile, README.md, src/Allele.cpp, src/AlleleParser.cpp, src/Fasta.cpp, src/LeftAlign.h, src/Makefile, src/Makefile.bamtools, src/Sample.cpp, src/bamleftalign.cpp, src/freebayes.cpp
This PR address issue [334](https://github.com/ekg/freebayes/issues/334) which noticed an issue with compiler flags not being passed to the SeqLib build. In addition:
-- separates CXXFLAGS from CFLAGS, and separates out the BAMTools build into ```src/Makefile.bamtools```
-- addresses a few minor compiler warnings
-- update to lighter SeqLib, which removes some heavy files from the repos
=> Improved build on OSX, update to lighter-weight SeqLib

src/AlleleParser.cpp, src/AlleleParser.h, src/Makefile
The allele parser could end up in a state where we deleted alignment before
their parsed alleles were removed from the list of registered alleles. Touching
these could in turn cause segfaults and other undefined behavior. This commit
ensures we clean up the pointers to the removed alleles correctly.
=> resolve #406

src/AlleleParser.cpp
It could also mean that alignments are corrupted.
In any case this should be clearer than the error was before. It referred to "cached reference sequence", which is a strange concept that doesn't really exist in freebayes anymore.
=> Give warning when there is a likely mismatch between alignment and reference sequence

src/LargeFileSupport.h, src/SegfaultHandler.cpp, src/SegfaultHandler.h
Changes to allow FreeBayes to be built with 64-bit Cygwin. Verified with GCC 6.4.0 on Windows 10.
=> Support for compilation with Cygwin 64

src/freebayes.cpp
This is as advertised. There are a number of applications (such as assembly polishing) where this matters. I don't think there are any clear drawbacks provided users consider the reference base in downstream analysis.
=> allow calling on N-matching reference bases

README.md
replaced occurrences of --haplotype-window in examples with --haplotype-length, as described in https://groups.google.com/d/msg/freebayes/FBOgspri3QE/Fw5fQ2CuFQUJ
=> replace --haplotype-window with --haplotype-length

src/AlleleParser.cpp
I am concerned that this fix may introduce an issue I am not aware of. It appears that before this change the haplotype length extension algorithm was accidentally disabled. This could affect the calling performance and I will need to validate that things don't go wrong in general.
=> resolve #437

README.md, src/Parameters.cpp
A lot of my support effort goes into correcting aggressive use of input filters. Here I am trying to improve the documentation and command line interface to explain the risks of this approach.
For example, I rename the popular allele observation exclusion filters `--no-snps`, `--no-indels`, `--no-mnps` and `--no-complex` to indicate what they are actually doing:
```
-I --throw-away-snp-obs     Remove SNP observations from input.                
-i --throw-away-indels-obs  Remove indel observations from input.
-X --throw-away-mnp-obs     Remove MNP observations from input.                
-u --throw-away-complex-obs Remove complex allele observations from input.      
```
Apparently most users believed these were filtering the _output_. They do not. They throw away read observations that …
=> clarify the effect of allele exclusion filters and document best practices

src/Parameters.cpp
This clarifies the delimiter in the CNV map BED file. (In response to a help request from a user working on mixed polyploids.)
=> clarify how to use the CNV map

Makefile, README.md, src/AlleleParser.cpp, src/AlleleParser.h, src/Makefile, src/Parameters.cpp, src/Parameters.h, src/freebayes.cpp, test/t/01_call_variants.t
This implements a new filter on the input of freebayes, `--skip-coverage`.
We throw out any alignments that overlap a position exceeding the given threshold. This is meant to speed processing through regions of very high coverage.
Note that `--max-coverage` is actually a downsampling routine, and doesn't have the desired effect in this case. It will limit computational costs in some sense though. This PR renames it to `--limit-coverage` in hopes of avoiding confusion. `--max-coverage` no longer exists, as the name is related to several confused interpretations.
=> Skip high coverage regions by throwing away reads when they overlap a position with coverage above a given threshold

src/AlleleParser.cpp, src/Makefile
This isn't the right solution (we get depths over our threshold) but it will avoid segfaulting when we start throwing out alignments that push us over our depth limit.
=> avoid position skipping logic when getting partial alignments covering haplotype calls

src/AlleleParser.cpp, src/AlleleParser.h, test/t/01_call_variants.t
This corrects a logic error when removing previously-registered alignments that overlap a given position.
I've also removed the Parameters object from the RegisteredAlignment object. This should save a huge amount of memory.
=> Skip coverage fixes

src/AlleleParser.cpp
This should reduce runtime by a significant amount, maybe almost half, in some workflows. I'm seeing this helping a bit in longer data. I need to check if there might be a reason to keep this code, but it doesn't seem there is because alleles are only generated once, and are otherwise "fit" to haplotypes without duplication.
=> can we get away without sorting and removing "non-unique" alleles?

src/CNV.cpp, src/CNV.h, test/t/01_call_variants.t
Current version has a bug: CNV map will not work with more than 1 entry per chromosome per sample.
Suppose the CNV-map looks like this:
```
chr1    0  100  sample1  4
chr1  100  200  sample1  6
```
All positions after position 100 will break on the first iteration and will get the default ploidy instead of 6.
=> CNV-map bug fix and speed-up

src/AlleleParser.cpp
If a read has no read group, when it is expected to have one, freebayes will print whole current sequence, which produces a very long error message.
I fixed it to output only chromosome name and position.
=> Shortening very long error message (read has no read group)

src/ResultData.cpp
When making a GVCF file, the QA and QR fields are printed as floating point numbers, despite being labeled as integers in the VCF header.
This doesn't show up unless calling high depth data, where the values will be high enough to be printed in scientific notation. In that case, the VCF can't be parsed by many (most?) tools, including VCF validator.
This fixes issues #557 and #558.
=> Fix: integer fields QA and QR are printed as floats in GVCF

scripts/freebayes-parallel
`freebayes-parallel`'s command-line help erroneously says that `coverage_to_regions.py` should take the `ref.fa` as input, when it really wants the fasta's index (i.e. `ref.fa.fai`as in the other examples).  The default command-line help for coverage_to_regions.py reads in part:
`coverage_to_regions.py  fasta_index num_regions >regions.bed`
=> coverage_to_regions.py should take ref.fa.fai

.gitmodules, meson.build
Bamtools is not used in the default build configuration and trying to build with -DHAVE_BAMTOOLS=1 results in errors.
This lead me to believe that it might be better to remove HAVE_BAMTOOLS support altogether, eventually.
The option -DHAVE_BAMTOOLS=1 causes this error:
```../src/AlleleParser.cpp: In member function ‘void AlleleParser::updateAlignmentQueue(long int, std::vector<Allele*>&, bool)’:
../src/AlleleParser.cpp:2023:34: error: ‘class BamTools::BamAlignment’ has no member named ‘SecondaryFlag’
2023 |             if (currentAlignment.SecondaryFlag()) {
|                                  ^~~~~~~~~~~~~
```
=> remove bamtools from the repo

src/AlleleParser.cpp
I encountered the following problem: if you pass `-@ input.vcf.gz` and input variant is not present in the reads, it may be too short in the output. Here is an example:
Input vcf file contains a single variant:
```
chr2    151598431       .       G       A
```
Output vcf file contains variant
```
chr2    151598431       .       GGC     GCC,A,GGA     0       .       ....;CIGAR=1M1X1M,1X,2M1X;
```
Second alternative allele is the input variant, and instead of `AGC` it is just `A`, additionally, CIGAR is just `1X` instead of `1X2M`.
I fixed the problem, but as I am not that familiar with freebayes code, maybe it is not the fastest/cleanest solution.
I can provide input data, if needed.
=> Bug fix: input allele is too short

.travis.yml, meson.build, src/AlleleParser.h, src/FBFasta.cpp, src/FBFasta.h, src/LeftAlign.h, src/bamleftalign.cpp, src/freebayes.cpp
Trying to find a solution #683. A header named Fasta.h is provided by vcflib/fastahack and the version in src/Fasta.h has a different interface than vcflib/fastahack/Fasta.h.
=> Fasta.h -> FBFasta.h and Travis experiment

examples/freebayes-env.yaml, examples/snakemake-freebayes-parallel.smk, scripts/fasta_generate_regions.py
Update the fasta_generate_regions.py to allow for splitting each chromosome in
the fasta into N equal chunks, as well as N size chunks. Also allows output to
bedfiles for use with the Snakemake example provided by sanjaynagi. With
default options, it still works with freebayes-parallel. Only uses Python
standard library.
=> Update fasta_generate_regions.py to work with Snakemake example

meson.build, meson_options.txt
1. Adds option to force use of submodule dependencies over system libraries. Forcing the use of the submodules should help in cases where there are all sorts of library versions in the user's search path (see #691).
2. Removes the bin/ folder that is not used anymore but has been mentioned in some support requests. (https://github.com/freebayes/freebayes/issues/688, https://groups.google.com/g/freebayes/c/metaBvKRkos)
=> Build option to skip system dependencies

src/AlleleParser.cpp, src/AlleleParser.h
This will ultimately require a much more extensive rewrite of the allele parsing logic.
There are a number of `vector<Allele>` copies that are extremely inefficient for long reads. They are bad enough for short reads that a rewrite is a good idea in general.
=> tweaks to improve performance on long reads

meson.build
`cc.find_library` can search for libraries via `-l<name>`. Previous names meant meson tried `-llibvcflib` and `-llibwfa2` which won't work.
=> meson: allow finding vcflib and wfa2 at non-standard paths

meson.build
Following errors were seen with `-Dprefer_system_deps=false`:
```
meson.build:179:26: ERROR: Unknown variable "smithwaterman_dep".
```
```
../src/DataLikelihood.cpp:3:10: fatal error: 'multipermute.h' file not found
```
=> meson: fix build with gitmodules
